"""init mysql

Revision ID: 1394d0f6ddfe
Revises: 
Create Date: 2026-01-04 12:53:55.443716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1394d0f6ddfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_advices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_advices', schema=None) as batch_op:
        batch_op.create_index('ix_advices_code_risk', ['diagnosis_code', 'risk_level'], unique=False)

    op.create_table('tbl_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tbl_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_users_email'), ['email'], unique=True)

    op.create_table('tbl_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['tbl_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_actor', ['actor_user_id'], unique=False)

    op.create_table('tbl_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['tbl_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('tbl_rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('expected_value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['tbl_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['tbl_symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'symptom_id', name='uq_rule_symptom')
    )
    with op.batch_alter_table('tbl_rule_conditions', schema=None) as batch_op:
        batch_op.create_index('ix_rule_conditions_rule_id', ['rule_id'], unique=False)
        batch_op.create_index('ix_rule_conditions_symptom_id', ['symptom_id'], unique=False)

    op.create_table('tbl_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('tbl_assessment_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('answer_bool', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['tbl_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['tbl_symptoms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'symptom_id', name='uq_assessment_symptom')
    )
    with op.batch_alter_table('tbl_assessment_answers', schema=None) as batch_op:
        batch_op.create_index('ix_answers_assessment_id', ['assessment_id'], unique=False)

    op.create_table('tbl_assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['tbl_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    with op.batch_alter_table('tbl_assessment_results', schema=None) as batch_op:
        batch_op.create_index('ix_results_assessment_id', ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_assessment_results', schema=None) as batch_op:
        batch_op.drop_index('ix_results_assessment_id')

    op.drop_table('tbl_assessment_results')
    with op.batch_alter_table('tbl_assessment_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_assessment_id')

    op.drop_table('tbl_assessment_answers')
    op.drop_table('tbl_user_roles')
    with op.batch_alter_table('tbl_rule_conditions', schema=None) as batch_op:
        batch_op.drop_index('ix_rule_conditions_symptom_id')
        batch_op.drop_index('ix_rule_conditions_rule_id')

    op.drop_table('tbl_rule_conditions')
    op.drop_table('tbl_role_permissions')
    with op.batch_alter_table('tbl_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_actor')
        batch_op.drop_index('ix_audit_action')

    op.drop_table('tbl_audit_logs')
    op.drop_table('tbl_assessments')
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_users_email'))

    op.drop_table('tbl_users')
    op.drop_table('tbl_symptoms')
    op.drop_table('tbl_rules')
    op.drop_table('tbl_roles')
    op.drop_table('tbl_permissions')
    with op.batch_alter_table('tbl_advices', schema=None) as batch_op:
        batch_op.drop_index('ix_advices_code_risk')

    op.drop_table('tbl_advices')
    # ### end Alembic commands ###
