"""add rule explanation_text

Revision ID: 7ab6a1d716ff
Revises: 80832d030052
Create Date: 2026-01-05 23:44:42.645221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab6a1d716ff'
down_revision = '80832d030052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rule_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rule_conditions', schema=None) as batch_op:
        batch_op.drop_column('explanation_text')

    # ### end Alembic commands ###
