"""add symptom info_yes info_no

Revision ID: 80832d030052
Revises: 1394d0f6ddfe
Create Date: 2026-01-04 16:40:26.298115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80832d030052'
down_revision = '1394d0f6ddfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_symptoms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_yes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_no', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_symptoms', schema=None) as batch_op:
        batch_op.drop_column('info_no')
        batch_op.drop_column('info_yes')

    # ### end Alembic commands ###
